import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const publicDir = path.resolve("public");
const siteUrl = (process.env.SITE_URL || "https://linux-scripts.susd12.org").replace(/\/$/, "");
const generatedMarker = "<!-- Generated by scripts/generate-index.mjs. Do not edit directly. -->";
const excludedDirs = new Set([".git", "node_modules"]);
const scriptExtensions = new Set([".sh"]);

function escapeHtml(value = "") {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#039;");
}

function titleCase(value) {
    return value
        .replace(/[-_]+/g, " ")
        .replace(/\b\w/g, (char) => char.toUpperCase());
}

function encodeUrlPath(relativePath) {
    return relativePath
        .split(path.sep)
        .filter(Boolean)
        .map(encodeURIComponent)
        .join("/");
}

function relativeUrl(relativePath, trailingSlash = false) {
    const encoded = encodeUrlPath(relativePath);
    if (!encoded) return "/";
    return `/${encoded}${trailingSlash ? "/" : ""}`;
}

function scriptMetadata(filePath, fileName) {
    const source = fs.readFileSync(filePath, "utf8");
    const metadata = {};

    for (const line of source.split(/\r?\n/).slice(0, 60)) {
        const match = line.match(/^\s*#\s*@([a-z0-9-]+)\s*:\s*(.*?)\s*$/i);
        if (match) metadata[match[1].toLowerCase()] = match[2];
    }

    const stat = fs.statSync(filePath);
    const sha256 = crypto.createHash("sha256").update(source).digest("hex");

    return {
        fileName,
        title: metadata.title || titleCase(fileName.replace(/\.sh$/i, "")),
        description: metadata.description || "Linux administration script.",
        platforms: metadata.platforms || "Linux",
        requiresRoot: /^(yes|true|1)$/i.test(metadata["requires-root"] || ""),
        size: stat.size,
        sha256,
    };
}

function formatBytes(bytes) {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getDirectoryEntries(directoryPath) {
    const entries = fs.readdirSync(directoryPath, { withFileTypes: true });

    const directories = entries
        .filter((entry) => entry.isDirectory() && !excludedDirs.has(entry.name) && !entry.name.startsWith("."))
        .map((entry) => entry.name)
        .sort((a, b) => a.localeCompare(b));

    const scripts = entries
        .filter((entry) => entry.isFile() && scriptExtensions.has(path.extname(entry.name).toLowerCase()))
        .map((entry) => scriptMetadata(path.join(directoryPath, entry.name), entry.name))
        .sort((a, b) => a.title.localeCompare(b.title));

    return { directories, scripts };
}

function countScriptsRecursively(directoryPath) {
    let count = 0;
    for (const entry of fs.readdirSync(directoryPath, { withFileTypes: true })) {
        if (entry.isDirectory() && !excludedDirs.has(entry.name) && !entry.name.startsWith(".")) {
            count += countScriptsRecursively(path.join(directoryPath, entry.name));
        } else if (entry.isFile() && scriptExtensions.has(path.extname(entry.name).toLowerCase())) {
            count += 1;
        }
    }
    return count;
}

function breadcrumbHtml(relativeDirectory) {
    const parts = relativeDirectory ? relativeDirectory.split(path.sep) : [];
    const links = ['<a href="/">Home</a>'];
    let runningPath = "";

    for (const part of parts) {
        runningPath = runningPath ? path.join(runningPath, part) : part;
        links.push(`<a href="${relativeUrl(runningPath, true)}">${escapeHtml(titleCase(part))}</a>`);
    }

    return links.join('<span class="crumb-separator" aria-hidden="true">/</span>');
}

function pageShell({ title, description, relativeDirectory = "", body }) {
    const pageTitle = relativeDirectory ? `${title} | SUSD Linux Scripts` : "SUSD Linux Scripts";

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="${escapeHtml(description)}">
    <title>${escapeHtml(pageTitle)}</title>
    <link rel="stylesheet" href="/site.css">
    <script src="/site.js" defer></script>
</head>
<body>
${generatedMarker}
<header class="site-header">
    <div class="container">
        <a class="brand" href="/">SUSD Linux Scripts</a>
        <p>Linux administration scripts maintained by Sunnyside Unified School District.</p>
    </div>
</header>
<main class="container">
    ${relativeDirectory ? `<nav class="breadcrumbs" aria-label="Breadcrumb">${breadcrumbHtml(relativeDirectory)}</nav>` : ""}
    <section class="page-intro">
        <h1>${escapeHtml(title)}</h1>
        <p>${escapeHtml(description)}</p>
    </section>
    ${body}
</main>
<footer class="site-footer">
    <div class="container">
        <p>Generated automatically from the contents of <code>/public</code> during deployment.</p>
    </div>
</footer>
</body>
</html>
`;
}

function directoryCards(directoryPath, relativeDirectory, directories) {
    if (!directories.length) return "";

    const cards = directories.map((directory) => {
        const childPath = path.join(relativeDirectory, directory);
        const count = countScriptsRecursively(path.join(directoryPath, directory));
        const countLabel = `${count} ${count === 1 ? "script" : "scripts"}`;
        return `
        <a class="folder-card" href="${relativeUrl(childPath, true)}">
            <span class="folder-icon" aria-hidden="true">📁</span>
            <span>
                <strong>${escapeHtml(titleCase(directory))}</strong>
                <small>${escapeHtml(countLabel)}</small>
            </span>
        </a>`;
    }).join("");

    return `
    <section aria-labelledby="folders-heading">
        <div class="section-heading">
            <h2 id="folders-heading">Folders</h2>
        </div>
        <div class="folder-grid">${cards}
        </div>
    </section>`;
}

function scriptCards(relativeDirectory, scripts) {
    if (!scripts.length) return "";

    const cards = scripts.map((script) => {
        const relativeFile = path.join(relativeDirectory, script.fileName);
        const urlPath = relativeUrl(relativeFile);
        const absoluteUrl = `${siteUrl}${urlPath}`;
        const tmpPath = `/tmp/${script.fileName}`;
        const installCommand = `curl -fsSL ${absoluteUrl} -o ${tmpPath} && ${script.requiresRoot ? "sudo " : ""}bash ${tmpPath}`;

        return `
        <article class="script-card">
            <div class="script-card-header">
                <div>
                    <h3><a href="${urlPath}">${escapeHtml(script.title)}</a></h3>
                    <p>${escapeHtml(script.description)}</p>
                </div>
                ${script.requiresRoot ? '<span class="badge">Root required</span>' : ""}
            </div>
            <dl class="metadata">
                <div><dt>File</dt><dd><code>${escapeHtml(script.fileName)}</code></dd></div>
                <div><dt>Platforms</dt><dd>${escapeHtml(script.platforms)}</dd></div>
                <div><dt>Size</dt><dd>${escapeHtml(formatBytes(script.size))}</dd></div>
            </dl>
            <div class="command-block">
                <div class="command-label">Download, inspect, and run</div>
                <div class="command-row">
                    <code>${escapeHtml(installCommand)}</code>
                    <button class="copy-button" type="button" data-copy="${escapeHtml(installCommand)}">Copy</button>
                </div>
            </div>
            <details class="checksum">
                <summary>SHA-256 checksum</summary>
                <code>${escapeHtml(script.sha256)}</code>
            </details>
            <div class="actions">
                <a class="button" href="${urlPath}">View raw script</a>
                <a class="button secondary" href="${urlPath}" download>Download .sh</a>
            </div>
        </article>`;
    }).join("");

    return `
    <section aria-labelledby="scripts-heading">
        <div class="section-heading">
            <h2 id="scripts-heading">Scripts</h2>
            <span>${scripts.length}</span>
        </div>
        <div class="script-list">${cards}
        </div>
    </section>`;
}

function generateDirectoryPage(directoryPath, relativeDirectory = "") {
    const { directories, scripts } = getDirectoryEntries(directoryPath);
    const isRoot = !relativeDirectory;
    const title = isRoot ? "Linux Script Library" : titleCase(path.basename(relativeDirectory));
    const description = isRoot
        ? "Browse reusable Linux administration scripts by category. Folder and script listings are generated automatically from the repository at deploy time."
        : `Browse scripts in the ${title} category.`;

    let body = directoryCards(directoryPath, relativeDirectory, directories);
    body += scriptCards(relativeDirectory, scripts);

    if (!directories.length && !scripts.length) {
        body = '<div class="empty-state"><p>No scripts or subfolders are currently available in this folder.</p></div>';
    }

    fs.writeFileSync(
        path.join(directoryPath, "index.html"),
        pageShell({ title, description, relativeDirectory, body }),
        "utf8",
    );

    for (const directory of directories) {
        generateDirectoryPage(path.join(directoryPath, directory), path.join(relativeDirectory, directory));
    }
}

if (!fs.existsSync(publicDir)) {
    throw new Error(`Public directory not found: ${publicDir}`);
}

generateDirectoryPage(publicDir);

const totalScripts = countScriptsRecursively(publicDir);
const topLevelFolders = getDirectoryEntries(publicDir).directories.length;
console.log(`Generated catalog pages for ${topLevelFolders} top-level folder(s) containing ${totalScripts} script(s).`);
